### ISSUE TITLE
我的工程 报错  #import <TiercelObjCBridge/TiercelObjCBridge-Swift.h> 找不到

### ISSUE THREAD

**Issue by ghost** [Danie1s/TiercelObjCBridge#1]
这个问题不知道自己的工程配置了什么东子，新的工程pod集成完毕，直接就可以编译通过公司项目一直找不到，不知道是怎么配置导致的 ，请问如果配置各个库需要哪些配置信息，我看下自己是不是配的冲突啦

**Comment by Danie1s** [comment]
刚才有人也有人跟我提过这个问题，你们是同一个人吗？
你新项目都可以集成，那肯定就是公司项目集成的问题，看看是不是多target导致的，其他方面我也帮不了你，具体问题具体分析
