### ISSUE TITLE
demo中可不可以增加个cell使用的例子？

### ISSUE THREAD

**Issue by heliang219** [Danie1s/TiercelObjCBridge#11]

**Comment by heliang219** [comment]
cell 复用的时候 会出现UI错乱的情况

**Comment by Danie1s** [comment]
demo 中本来就有

**Comment by heliang219** [comment]
我是说你这个oc版本里 我用了你这个桥接 然后参照你swift版里用cell的方式 复用的时候出现个问题 就是进度条 会显示滑上去的那个cell的进度 这个需要怎么处理下啊？

**Comment by Danie1s** [comment]
参照 Swift 版本就行，cell 保存着一个 task，复用的时候清除之前的 task 回调
