### ISSUE TITLE
开启多个下载时卡顿

### ISSUE THREAD

**Issue by leeCoding** [Danie1s/TiercelObjCBridge#9]
开启多个下载时卡线程，放在异步中同样，卡顿有点明显，另外在使用开始全部方法时，我看源码中会拿到所有的下载资源组，然后调开始下载方法， 这个地方是不是可以优化下，筛选非下载成功的进行下载，而不是把所有的资源再次调用开始下载呢

**Comment by Danie1s** [comment]
抱歉，这个库目前依赖的是 Tiecel 旧版，新版的 Tiecel已经进行了优化，但这个库我还没有时间进行更新，望见谅
